ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 3000
    database:
        url: "jdbc:postgresql://ktor-cart-db-1:5432/cart"
        driver: org.postgresql.Driver
        user: postgres
        password: example
